/* ------------------------------------------------------------------ *
 * Display-name moderation checks.
 *
 * Run with: npm run test:names
 *
 * Four parts:
 *
 *   1. EVASION      every blocked term is run through every evasion class
 *                   the brief names — case, leetspeak, repeated characters,
 *                   separators, zero-width characters, Unicode confusables,
 *                   full-width forms — and each result must be caught.
 *
 *   2. INNOCENCE    a list of real place names, surnames and ordinary words
 *                   that contain or collapse onto a blocked term must all
 *                   pass. The Scunthorpe problem, tested rather than
 *                   asserted. The names checked are printed by name.
 *
 *   3. ENFORCEMENT  the database paths: a blocked name is not stored, a
 *                   blocked name already in a row is not returned, and name
 *                   changes run out of budget.
 *
 *   4. CONTAINMENT  the built client bundle is searched for the blocklist,
 *                   both as plaintext and as the encoded blobs an accidental
 *                   import would actually produce.
 *
 * NOTE ON THIS FILE: it contains no slur. Every evasion case is generated by
 * transforming a term decoded from the blocklist at runtime, which is both
 * cleaner to read and a far wider test than hand-written examples — it covers
 * every term rather than the two or three someone thought to type.
 * ------------------------------------------------------------------ */

import { readdirSync, readFileSync, mkdirSync, rmSync, statSync } from 'node:fs'
import { join, resolve } from 'node:path'

const dbFile = resolve('data/names-test.db')
const financeFile = resolve('data/names-test-finance.db')
mkdirSync(resolve('data'), { recursive: true })
for (const base of [dbFile, financeFile]) {
  for (const suffix of ['', '-wal', '-shm']) {
    try { rmSync(`${base}${suffix}`) } catch { /* nothing to remove */ }
  }
}
process.env.WALLY_DB_PATH = dbFile
process.env.WALLY_FINANCE_DB_PATH = financeFile
process.env.WALLY_DEV_SESSIONS = '1'

let passed = 0
const failures: string[] = []

function check(name: string, condition: boolean, detail = '') {
  if (condition) passed++
  else failures.push(`${name}${detail ? ` — ${detail}` : ''}`)
}

function eq(name: string, actual: unknown, expected: unknown) {
  check(name, Object.is(actual, expected), `expected ${JSON.stringify(expected)}, got ${JSON.stringify(actual)}`)
}

/* ------------------------------------------------------------------ *
 * Evasion generators. Each takes a plain term and returns the spelling an
 * attacker would actually try.
 * ------------------------------------------------------------------ */

const LEET: Record<string, string> = { a: '4', b: '8', e: '3', g: '9', i: '1', l: '1', o: '0', s: '5', t: '7', z: '2' }
const SYMBOL: Record<string, string> = { a: '@', e: '3', i: '!', o: '0', s: '$', t: '+', c: '(' }
const CYRILLIC: Record<string, string> = {
  a: 'а', b: 'в', c: 'с', e: 'е', h: 'н', i: 'і', j: 'ј', k: 'к', m: 'м',
  n: 'п', o: 'о', p: 'р', r: 'г', s: 'ѕ', t: 'т', x: 'х', y: 'у',
}
const VOWELS = new Set(['a', 'e', 'i', 'o', 'u'])

const substitute = (term: string, table: Record<string, string>) => [...term].map(ch => table[ch] ?? ch).join('')
const fullWidth = (term: string) =>
  [...term]
    .map(ch =>
      ch >= 'a' && ch <= 'z'
        ? String.fromCodePoint(0xff41 + (ch.codePointAt(0)! - 97))
        : ch >= '0' && ch <= '9'
          ? String.fromCodePoint(0xff10 + (ch.codePointAt(0)! - 48))
          : ch,
    )
    .join('')
const separate = (term: string, glue: string) => [...term].join(glue)
const stretchVowels = (term: string) => [...term].map(ch => (VOWELS.has(ch) ? ch.repeat(3) : ch)).join('')
const alternateCase = (term: string) => [...term].map((ch, i) => (i % 2 ? ch.toUpperCase() : ch)).join('')

/**
 * `substringOnly` marks a transform that buries the term inside other letters.
 * Those are only expected to be caught for the substring tier: catching them
 * for the whole-token tier is the same thing as rejecting "Scunthorpe", so it
 * is asserted as a deliberate limit further down rather than as a pass.
 */
type Evasion = { label: string; apply: (term: string) => string; substringOnly?: true }

const EVASIONS: readonly Evasion[] = [
  { label: 'plain spelling', apply: term => term },
  { label: 'uppercase', apply: term => term.toUpperCase() },
  { label: 'alternating case', apply: alternateCase },
  { label: 'leetspeak digits (1/l/i, 3/e, 0/o, 4/a, 5/s)', apply: term => substitute(term, LEET) },
  { label: 'leetspeak symbols ($/s, @/a, +/t, !/i)', apply: term => substitute(term, SYMBOL) },
  { label: 'repeated characters', apply: stretchVowels },
  { label: 'separator: space', apply: term => separate(term, ' ') },
  { label: 'separator: full stop', apply: term => separate(term, '.') },
  { label: 'separator: hyphen', apply: term => separate(term, '-') },
  { label: 'separator: underscore', apply: term => separate(term, '_') },
  { label: 'separator: zero-width space', apply: term => separate(term, '\u200b') },
  { label: 'separator: zero-width joiner', apply: term => separate(term, '\u200d') },
  { label: 'separator: soft hyphen', apply: term => separate(term, '\u00ad') },
  { label: 'Cyrillic confusables (а е о р с …)', apply: term => substitute(term, CYRILLIC) },
  { label: 'full-width forms', apply: fullWidth },
  { label: 'leetspeak + repeats + case', apply: term => alternateCase(stretchVowels(substitute(term, LEET))) },
  { label: 'confusables + separators', apply: term => separate(substitute(term, CYRILLIC), '.') },
  { label: 'buried inside other letters', apply: term => `xX${term}Xx`, substringOnly: true },
  { label: 'buried, leeted and stretched', apply: term => `zz${stretchVowels(substitute(term, LEET))}zz`, substringOnly: true },
]

/* ------------------------------------------------------------------ *
 * Innocent names. Printed in the report, so they are all safe to read.
 * ------------------------------------------------------------------ */

const INNOCENT_NAMES: readonly string[] = [
  // British place names, the classic false positives
  'Scunthorpe', 'Penistone', 'Clitheroe', 'Cockermouth', 'Cockfosters', 'Lightwater',
  'Sussex', 'Essex', 'Middlesex', 'Wessex',
  // countries and regions whose names collapse onto a slur
  'Nigeria', 'Nigerian', 'Niger', 'Pakistan', 'Pakistani', 'Assam',
  // real surnames and given names
  'Cockburn', 'Woodcock', 'Hancock', 'Babcock', 'Hitchcock', 'Peacock', 'Cocker',
  'Cumming', 'Cummings', 'Dickens', 'Dickinson', 'Benedict', 'Nigel', 'Nigar',
  'Titus', 'Titania', 'Sexton', 'Cooney', 'Van Dyke', 'Dick Van Dyke', 'Cassandra',
  'Cassidy', 'Assange', 'Fagotti', 'Thomas', 'Aaron', 'Anne-Marie', "O'Brien",
  'Ana Lucia', 'Ana L', 'Jose Ramirez', 'Etienne', 'Zoe', 'Ali', 'Mohammed', 'Xi',
  // ordinary vocabulary a player might reasonably choose
  'Assassin', 'Analyst', 'Analysis', 'Canal Street', 'Banal', 'Cucumber', 'Document',
  'Therapist', 'Suspicious', 'Spicer', 'Spices', 'Spicy', 'Raccoon', 'Tycoon',
  'Cocoon', 'Lagoon', 'Sauerkraut', 'Shiitake', 'Titan', 'Constitution', 'Attitude',
  'Entities', 'Identities', 'Quantities', 'Grapes', 'Drapes', 'Trapeze', 'Shoe',
  'Compass', 'Classic', 'Glasshouse', 'Grasshopper', 'Embassy', 'Cocktail',
  'Shuttlecock', 'Homage', 'Homogeneous', 'Sextant', 'Competition', 'Verdict',
  'Torpedo', 'Pedometer', 'Uranus', 'Despicable', 'Conspicuous', 'Spicier',
  'Swoop', 'Squawk', 'Yiddish', 'Negroni', 'Montenegro', 'Nazir', 'Abbot',
  'Fire Retardant', 'Speedo', 'Wankel Engine', 'Milford', 'Pussycat',
  // non-Latin scripts must not be mangled into a match by the confusable table
  'Владимир', 'Екатерина', '山田太郎', 'こんにちは', 'Ολυμπία', 'محمد', 'שלום',
  // the names this world actually ships with
  'Moth', 'Bramble', 'Cinder', 'Orbit', 'Wayfinder', 'Traveller', 'Ash', 'Birch',
]

async function main() {
  const { ALWAYS_TERMS, WORD_TERMS } = await import('../src/server/moderation/blocklist')
  const {
    NEUTRAL_DISPLAY_NAME,
    blocklistSize,
    clearNameVerdictCache,
    nameFingerprint,
    normaliseForMatch,
    publicDisplayName,
    screenDisplayName,
  } = await import('../src/server/moderation/names')
  const { PLAYER_NAME_MAX, sanitisePlayerName } = await import('../src/shared/profile')

  console.log('Voxels · display-name moderation')
  console.log(`  blocklist   ${blocklistSize.always} substring terms · ${blocklistSize.word} whole-token terms · ${blocklistSize.innocent} allowlisted words`)
  console.log('')

  /* ---- 1. evasion ---------------------------------------------------- */

  const TERMS = [...ALWAYS_TERMS, ...WORD_TERMS]
  let cases = 0
  let caught = 0
  let skippedForLength = 0
  const missedBy = new Map<string, number>()

  for (const evasion of EVASIONS) {
    let evasionCases = 0
    let evasionCaught = 0
    for (const term of evasion.substringOnly ? ALWAYS_TERMS : TERMS) {
      const attempt = evasion.apply(term)
      // A real name is clamped before it is screened, and a clamp can cut a
      // term in half. Cases that could not survive the clamp are not evasions,
      // they are different strings, so they are counted and skipped.
      if (sanitisePlayerName(attempt).length < attempt.trim().length) {
        skippedForLength += 1
        continue
      }
      cases += 1
      evasionCases += 1
      if (!screenDisplayName(attempt).ok) {
        caught += 1
        evasionCaught += 1
      }
    }
    const missed = evasionCases - evasionCaught
    if (missed > 0) missedBy.set(evasion.label, missed)
    check(`evasion class caught: ${evasion.label}`, missed === 0, `${missed}/${evasionCases} spellings slipped through`)
    console.log(`  ${missed === 0 ? 'ok      ' : 'FAIL    '} ${String(evasionCaught).padStart(3)}/${String(evasionCases).padEnd(3)} caught — ${evasion.label}`)
  }

  console.log('')
  console.log(`  evasion cases tested: ${cases} · caught: ${caught} · missed: ${cases - caught} · skipped (would be truncated by the ${PLAYER_NAME_MAX}-character clamp): ${skippedForLength}`)
  check('every generated evasion spelling is caught', caught === cases, `${cases - caught} missed`)

  /*
   * The stated limit of the whole-token tier, asserted rather than discovered.
   *
   * A term in that tier buried inside other letters is NOT caught, and that is
   * the price of "Scunthorpe" passing. It is checked here so the trade-off
   * cannot quietly change in either direction without a test failing.
   */
  const buriedWordTier = WORD_TERMS.map(term => `xX${term}Xx`).filter(attempt => !screenDisplayName(attempt).ok)
  eq(`the whole-token tier does not match inside other letters (${WORD_TERMS.length} terms — documented limit)`, buriedWordTier.length, 0)
  console.log(`  note     ${WORD_TERMS.length} whole-token terms are matched as tokens only — a buried spelling of those is NOT caught, which is what lets Scunthorpe through`)

  // The normaliser itself: the point of it is that these all land on one string.
  // Sampled from terms with no `l` and no `ph`, because those are exactly the
  // two cases where one term legitimately has two comparison forms.
  const sample = ALWAYS_TERMS.find(term => term.length >= 6 && /^[a-z]+$/.test(term) && !term.includes('l') && !term.includes('ph'))!
  const forms = [
    sample,
    sample.toUpperCase(),
    substitute(sample, LEET),
    separate(sample, '.'),
    separate(sample, '\u200b'),
    substitute(sample, CYRILLIC),
    fullWidth(sample),
  ]
  const tights = new Set(forms.map(form => normaliseForMatch(form).tight))
  eq('every evasion of one term normalises to a single comparison form', tights.size, 1)

  /* ---- 2. innocence -------------------------------------------------- */

  const wrongly: string[] = []
  for (const name of INNOCENT_NAMES) {
    if (!screenDisplayName(name).ok) wrongly.push(name)
  }
  check('no innocent name is rejected', wrongly.length === 0, `rejected: ${wrongly.join(', ')}`)
  console.log(`  ${wrongly.length === 0 ? 'ok      ' : 'FAIL    '} ${INNOCENT_NAMES.length} innocent names all pass${wrongly.length ? ` (rejected: ${wrongly.join(', ')})` : ''}`)

  // The original text survives untouched when it passes. A filter that
  // "cleans" a name it accepted would be a bug of its own.
  eq('an accepted name is returned verbatim', publicDisplayName('Scunthorpe Analyst'), 'Scunthorpe Analyst')
  eq('an accepted name with punctuation is returned verbatim', publicDisplayName("Anne-Marie O'Brien"), "Anne-Marie O'Brien")
  eq('an empty stored name falls back to the neutral name', publicDisplayName(''), NEUTRAL_DISPLAY_NAME)
  check('a non-string is not screened as a name', screenDisplayName(undefined).ok)

  // A name with no Latin content at all has nothing to compare, and must not
  // be rejected for it.
  check('a CJK-only name passes', screenDisplayName('山田太郎').ok)
  check('an emoji-only name passes', screenDisplayName('✦✦✦').ok)

  // Fingerprints identify without disclosing.
  const fp = nameFingerprint('Scunthorpe')
  check('a fingerprint is a truncated hash, not the name', fp.startsWith('sha256:') && !fp.includes('cunt') && fp.length < 32)
  eq('the same name fingerprints the same way twice', nameFingerprint('Scunthorpe'), fp)

  /* ---- 3. enforcement ------------------------------------------------ */

  const { ensureAccount, accountByPlayer, saveLoadout } = await import('../src/server/pvp/ids')
  const { clearBuckets } = await import('../src/server/net')
  const { db } = await import('../src/server/pvp/schema')
  const { DEFAULT_PROFILE } = await import('../src/shared/profile')

  const loadout = { character: 'MOTH' as const, style: DEFAULT_PROFILE.style, level: 1, ranks: { Q: 0, W: 0, E: 0, R: 0 } }
  // The worst spelling available, assembled at runtime from the list rather
  // than typed here.
  const blockedName = substitute(ALWAYS_TERMS.find(term => term.length >= 6)!, LEET).toUpperCase()

  clearBuckets()
  const account = ensureAccount('devnametest')
  const result = saveLoadout(account.player_id, blockedName, loadout)
  eq('the socket path refuses to store a blocked name', result.nameOutcome, 'blocked')
  eq('the account keeps the name it had', result.name, DEFAULT_PROFILE.playerName)
  const afterBlocked = db.prepare<[string], { display_name: string }>('select display_name from pvp_accounts where player_id = ?').get(account.player_id)
  eq('nothing blocked reached the row', afterBlocked?.display_name, DEFAULT_PROFILE.playerName)

  eq('a clean name is stored', saveLoadout(account.player_id, 'Birchwarden', loadout).nameOutcome, 'stored')
  eq('the clean name is what comes back out', accountByPlayer(account.player_id)?.display_name, 'Birchwarden')
  eq('re-sending the same name is not a change', saveLoadout(account.player_id, 'Birchwarden', loadout).nameOutcome, 'unchanged')

  // The broadcast layer, which is the part that matters for a row that already
  // exists. Written straight to the table, exactly as a pre-moderation row is.
  db.prepare('update pvp_accounts set display_name = ? where player_id = ?').run(blockedName, account.player_id)
  clearNameVerdictCache()
  eq('a blocked name already in the database is never returned', accountByPlayer(account.player_id)?.display_name, NEUTRAL_DISPLAY_NAME)
  db.prepare('update pvp_accounts set display_name = ? where player_id = ?').run('Birchwarden', account.player_id)
  clearNameVerdictCache()

  // Rate limiting. Eight changes, then the budget is gone — and the ninth
  // keeps the name it had rather than accepting the new one.
  clearBuckets()
  const burst = ensureAccount('devnameburst')
  const outcomes: string[] = []
  for (let i = 0; i < 12; i++) outcomes.push(saveLoadout(burst.player_id, `Warden${i}`, loadout).nameOutcome)
  eq('the first eight name changes are accepted', outcomes.slice(0, 8).every(o => o === 'stored'), true)
  eq('the ninth is rate limited', outcomes[8], 'rate_limited')
  eq('a rate-limited change does not take effect', accountByPlayer(burst.player_id)?.display_name, 'Warden7')
  clearBuckets()

  /* ---- 4. containment ------------------------------------------------ */

  const source = readFileSync('src/server/moderation/blocklist.ts', 'utf8')
  const blobs = [...source.matchAll(/'([A-Za-z0-9+/=]{40,})'/g)].map(match => match[1])
  check('the blocklist is stored encoded, not as plain source', blobs.length > 0)
  // Word-boundary, not substring: the allowlist and the comments legitimately
  // contain innocent words that a term sits inside, which is the whole point of
  // them. "Therapist" is allowed to mention what it protects against.
  const inSource = TERMS.filter(term => term.length >= 6 && new RegExp(`\\b${term}\\b`, 'i').test(source))
  check('no blocked term appears as a word in the blocklist source', inSource.length === 0, `${inSource.length} found`)

  const DIRS = ['dist', 'dist-dev']
  const plainNeedles = TERMS.filter(term => term.length >= 6)
  let scannedDirs = 0
  for (const dir of DIRS) {
    let files: string[]
    try {
      const walk = (current: string): string[] =>
        readdirSync(current).flatMap(entry => {
          const path = join(current, entry)
          return statSync(path).isDirectory() ? walk(path) : [path]
        })
      files = walk(dir)
    } catch {
      console.log(`  skip     ${dir} — not built, cannot check for a blocklist leak`)
      continue
    }
    scannedDirs += 1
    const text = files.map(path => readFileSync(path, 'utf8')).join('\n').toLowerCase()
    const leakedBlob = blobs.filter(blob => text.includes(blob.toLowerCase()))
    const leakedPlain = plainNeedles.filter(term => text.includes(term))
    check(`${dir}: the encoded blocklist is not in the bundle`, leakedBlob.length === 0, `${leakedBlob.length} blob(s) found`)
    check(`${dir}: no blocked term is in the bundle as plain text`, leakedPlain.length === 0, `${leakedPlain.length} term(s) found`)
    console.log(`  ${leakedBlob.length + leakedPlain.length === 0 ? 'ok      ' : 'FAIL    '} ${dir} — ${files.length} files scanned for ${blobs.length} encoded blob(s) and ${plainNeedles.length} plaintext terms`)
  }
  if (scannedDirs === 0) console.log('  NOTE: no build output found. Run `npm run build` first for the containment check to mean anything.')

  console.log('')
  console.log(`${failures.length === 0 ? 'PASS' : 'FAIL'} — ${passed} checks passed, ${failures.length} failed`)
  for (const failure of failures) console.log(`  × ${failure}`)
  if (missedBy.size) {
    console.log('  evasion classes with gaps:')
    for (const [label, count] of missedBy) console.log(`    ${label}: ${count}`)
  }
  process.exit(failures.length === 0 ? 0 : 1)
}

main().catch(error => {
  console.error(error)
  process.exit(1)
})
